In [45]:
#Import libraries
import googlemaps
import requests
from itertools import tee
import time
import pandas as pd
apikey= 'Type your Google Maps API key here'

In [46]:
#Instantiate google maps 
gmaps = googlemaps.Client(key=apikey)

In [47]:
#Create function to turn data pulled from API into a dataframe
def create_df(places_result):
    #create empty list to hold informaion for each column
    geometry = []
    name = []
    vicinity = []
    types = []
    #Create a for loop to iterate over dictionary and append to lists.
    for place in places_result['results']:
        geometry.append(place['geometry'])
        name.append(place['name'])
        vicinity.append(place['vicinity'])
        types.append(place['types'])
    #Turn lists into a dataframe
    df = pd.DataFrame([geometry,name,vicinity,types])
    df = df.T
    df.columns = ['geometry','name','vicinity','types']
    return df

In [48]:
#Create function to pull from Google maps API and return a dataframe.
#Inputs will be the loc('latitude,longitude'), radius to search, and place type.
def find_nearby(loc,rad,place_types):
    #Pull data from Google API and use create_df to create dataframe.
    places_result = gmaps.places_nearby(location = loc,radius=rad, type=place_types,page_token=None)
    df= create_df(places_result)
    #Call next page and store as after
    after=places_result.get('next_page_token',None)
    time.sleep(3)
    #repeat this process until there are no more pages to pull from.
    while after !=None:
        places_result = gmaps.places_nearby(location = loc,radius=rad, type=place_types,page_token=after)
        df = df.append(create_df(places_result))
        after=places_result.get('next_page_token',None)
        time.sleep(3) # Set a 3 second delay between requests.
    df.reset_index(drop=True,inplace=True)
    return df

In [36]:
df = find_nearby('29.9511,-90.0715',8000,'hospital')

                                             geometry  \
0   {'location': {'lat': 29.9177486, 'lng': -90.12...
1   {'location': {'lat': 29.8917868, 'lng': -90.09...
2   {'location': {'lat': 29.9556817, 'lng': -90.07...
3   {'location': {'lat': 29.9266229, 'lng': -90.09...
4   {'location': {'lat': 29.9177892, 'lng': -90.12...
5   {'location': {'lat': 29.9395701, 'lng': -90.10...
6   {'location': {'lat': 29.9372464, 'lng': -90.10...
7   {'location': {'lat': 29.8906192, 'lng': -90.09...
8   {'location': {'lat': 29.9372263, 'lng': -90.07...
9   {'location': {'lat': 29.924955, 'lng': -90.093...
10  {'location': {'lat': 29.960785, 'lng': -90.144...
11  {'location': {'lat': 29.956131, 'lng': -90.074...
12  {'location': {'lat': 29.9557828, 'lng': -90.07...
13  {'location': {'lat': 29.975359, 'lng': -90.097...
14  {'location': {'lat': 29.962809, 'lng': -90.153...
15  {'location': {'lat': 29.9177892, 'lng': -90.12...
16  {'location': {'lat': 29.89340499999999, 'lng':...
17  {'location': {'lat': 29.9725706, 'lng': -90.09...
18  {'location': {'lat': 29.95957689999999, 'lng':...
19  {'location': {'lat': 29.96666500000001, 'lng':...

                                                 name  \
0                     Children's Hospital New Orleans
1                       West Jefferson Medical Center
2                               Tulane Medical Center
3                   Internal Medicine Specialist Inc.
4                                              CHNOLA
5      Planned Parenthood - New Orleans Health Center
6                                     Ochsner Baptist
7                              Heart Clinic Louisiana
8               Center for Restorative Breast Surgery
9                              Curahealth New Orleans
10                                  Luis Teixeira, MD
11                               Tulane Cancer Center
12            Fresenius Medical Care at Tulane Acutes
13               DaVita Crescent City Dialysis Center
14                     Ochsner Extended Care Hospital
15                             LSU Healthcare Network
16  Jefferson Parish Human Services Authority, Wes...
17                            Willis and Buckley, APC
18                              Family Asthma Allergy
19           New Orleans Center for Clinical Research

                                            vicinity  \
0                 200 Henry Clay Avenue, New Orleans
1             1101 Medical Center Boulevard, Marrero
2                    1415 Tulane Avenue, New Orleans
3                  3525 Prytania Street, New Orleans
4           5720, 200 Henry Clay Avenue, New Orleans
5   4636 South Claiborne Avenue Ste 100, New Orleans
6                  2700 Napoleon Avenue, New Orleans
7             1111 Medical Center Boulevard, Marrero
8             1717 Saint Charles Avenue, New Orleans
9                  3601 Coliseum Street, New Orleans
10                 1514 Jefferson Highway, Jefferson
11             150 South Liberty Street, New Orleans
12            1415 Tulane Avenue (hc25), New Orleans
13         3909 Bienville Street Ste 1b, New Orleans
14               2614 Jefferson Highway, New Orleans
15                200 Henry Clay Avenue, New Orleans
16                 5001 Westbank Expressway, Marrero
17                    3723 Canal Street, New Orleans
18                                       New Orleans
19                    2820 Canal Street, New Orleans

                                                types
0        [hospital, point_of_interest, establishment]
1        [hospital, point_of_interest, establishment]
2        [hospital, point_of_interest, establishment]
3   [hospital, health, point_of_interest, establis...
4        [hospital, point_of_interest, establishment]
5        [hospital, point_of_interest, establishment]
6        [hospital, point_of_interest, establishment]
7        [hospital, point_of_interest, establishment]
8   [doctor, hospital, health, point_of_interest, ...
9        [hospital, point_of_interest, establishment]
10  [hospital, doctor, health, point_of_interest, ...
11       [hospital, point_of_interest, establishment]
12  [doctor, hospital, health, point_of_interest, ...
13  [hospital, health, point_of_interest, establis...
14  [hospital, health, point_of_interest, establis...
15       [hospital, point_of_interest, establishment]
16  [hospital, health, point_of_interest, establis...
17  [insurance_agency, lawyer, hospital, car_repai...
18       [hospital, point_of_interest, establishment]
19       [hospital, point_of_interest, establishment]

In [37]:
df.head()

,geometry,name,vicinity,types
0,"{'location': {'lat': 29.9177486, 'lng': -90.12...",Children's Hospital New Orleans,"200 Henry Clay Avenue, New Orleans","[hospital, point_of_interest, establishment]"
1,"{'location': {'lat': 29.8917868, 'lng': -90.09...",West Jefferson Medical Center,"1101 Medical Center Boulevard, Marrero","[hospital, point_of_interest, establishment]"
2,"{'location': {'lat': 29.9556817, 'lng': -90.07...",Tulane Medical Center,"1415 Tulane Avenue, New Orleans","[hospital, point_of_interest, establishment]"
3,"{'location': {'lat': 29.9266229, 'lng': -90.09...",Internal Medicine Specialist Inc.,"3525 Prytania Street, New Orleans","[hospital, health, point_of_interest, establis..."
4,"{'location': {'lat': 29.9177892, 'lng': -90.12...",CHNOLA,"5720, 200 Henry Clay Avenue, New Orleans","[hospital, point_of_interest, establishment]"

In [38]:
df.tail()

,geometry,name,vicinity,types
15,"{'location': {'lat': 29.9613165, 'lng': -90.14...",OCHSNER MAIN,"Collins C. Diboll Drive, Jefferson","[hospital, point_of_interest, establishment]"
16,"{'location': {'lat': 29.8906129, 'lng': -90.09...",West Jefferson Urology Specialists,"1111 Medical Center Boulevard #650, Marrero","[hospital, point_of_interest, establishment]"
17,"{'location': {'lat': 29.9616798, 'lng': -90.14...",Ochsner Multi-Organ Transplant Institute,"1514 Jefferson Highway, Jefferson","[hospital, doctor, health, point_of_interest, ..."
18,"{'location': {'lat': 29.9640732, 'lng': -90.14...",Ochsner Center for Primary Care and Wellness,"1401 Jefferson Highway, Jefferson","[hospital, point_of_interest, establishment]"
19,"{'location': {'lat': 29.9635129, 'lng': -90.14...",PHARMACY & WELLNESS - PRIMARY CARE,"1401 Jefferson Highway, Jefferson","[pharmacy, hospital, health, store, point_of_i..."

In [42]:
df.shape

(60, 4)

In [106]:
#Loop through the geometry column of dataframe and create new latitude and longitude columns.
lat_list=[]
lng_list=[]
for place in df['geometry']:
    lat_list.append(place['location']['lat'])
    lng_list.append(place['location']['lng'])

place_df = pd.DataFrame([lat_list,lng_list]).T
place_df.columns=['lat','lng']

#Merge latitude and longitude to dataframe.
df= df.merge(place_df,left_index=True, right_index=True)

In [44]:
#export to csv.
df.to_csv('./hospitals.csv', index = False)

In [69]:
firestaton_df = find_nearby('29.9511,-90.0715',6000,'fire_station')

In [60]:
firestaton_df.reset_index(drop=True, inplace= True)

In [62]:
firestaton_df.head()

,geometry,name,vicinity,types
0,"{'location': {'lat': 29.95414740000001, 'lng':...",New Orleans Fire Department,"317 Decatur Street, New Orleans","[fire_station, point_of_interest, establishment]"
1,"{'location': {'lat': 29.95720500000001, 'lng':...",Fire Station 14,New Orleans,"[fire_station, point_of_interest, establishment]"
2,"{'location': {'lat': 29.94844839999999, 'lng':...",New Orleans Fire Engine 20,"425 Opelousas Avenue, New Orleans","[fire_station, point_of_interest, establishment]"
3,"{'location': {'lat': 29.9478144, 'lng': -90.07...",NOFD Fire Station Squad 2/Rescue 2,"801 Girod Street, New Orleans","[fire_station, point_of_interest, establishment]"
4,"{'location': {'lat': 29.94158549999999, 'lng':...",Cease Fire,"1417 Oretha Castle Haley Boulevard, New Orleans","[fire_station, point_of_interest, establishment]"

In [63]:
firestaton_df.shape

(56, 4)